// <auto-generated />
using System;
using BusinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(TkdecorContext))]
    [Migration("20230706163521_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Article", b =>
                {
                    b.Property<long>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("article_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ArticleId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<bool>("IsPublish")
                        .HasColumnType("bit")
                        .HasColumnName("is_publish");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("slug");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ArticleId")
                        .HasName("PK__Article__CC36F660180F7E7F");

                    b.HasIndex(new[] { "Slug" }, "IX_Article_slug")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_Article_user_id");

                    b.ToTable("Article", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Cart", b =>
                {
                    b.Property<long>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("CartId")
                        .HasName("PK__Cart__2EF52A27823B5610");

                    b.HasIndex(new[] { "ProductId" }, "IX_Cart_product_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Cart_user_id");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__D54EE9B430138B56");

                    b.HasIndex(new[] { "Name" }, "IX_Category_name")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Chat", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint")
                        .HasColumnName("receiver_id");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("MessageId")
                        .HasName("PK__Message__0BBF6EE6112EA443");

                    b.HasIndex(new[] { "ReceiverId" }, "IX_Message_receiver_id");

                    b.HasIndex(new[] { "SenderId" }, "IX_Message_sender_id");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Coupon", b =>
                {
                    b.Property<long>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CouponId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("code");

                    b.Property<long>("CouponTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(8, 0)")
                        .HasColumnName("max_value");

                    b.Property<int>("RemainingUsageCount")
                        .HasColumnType("int")
                        .HasColumnName("remaining_usage_count");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(8, 0)")
                        .HasColumnName("value");

                    b.HasKey("CouponId")
                        .HasName("PK__Coupon__58CF6389A836CD8D");

                    b.HasIndex(new[] { "Code" }, "IX_Coupon_code")
                        .IsUnique();

                    b.HasIndex(new[] { "CouponTypeId" }, "IX_Coupon_coupon_type_id");

                    b.ToTable("Coupon", (string)null);
                });

            modelBuilder.Entity("BusinessObject.CouponType", b =>
                {
                    b.Property<long>("CouponTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CouponTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("CouponTypeId")
                        .HasName("PK__CouponTy__AD2AFC0A104B34A3");

                    b.ToTable("CouponType", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842F2D0624C3");

                    b.HasIndex(new[] { "UserId" }, "IX_Notification_user_id");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<long?>("CouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long>("OrderStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_status_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("phone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__465962292D23A46C");

                    b.HasIndex(new[] { "CouponId" }, "IX_Order_coupon_id");

                    b.HasIndex(new[] { "OrderStatusId" }, "IX_Order_order_status_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Order_user_id");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OrderDetail", b =>
                {
                    b.Property<long>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderDetailId"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("PaymentPrice")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("payment_price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__3C5A4080BBA82BF6");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderDetail_order_id");

                    b.HasIndex(new[] { "ProductId" }, "IX_OrderDetail_product_id");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("BusinessObject.OrderStatus", b =>
                {
                    b.Property<long>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("OrderStatusId")
                        .HasName("PK__OrderSta__A499CF231D746F37");

                    b.ToTable("OrderStatus", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 0)")
                        .HasColumnName("price");

                    b.Property<long?>("Product3DModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_3d_model_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__47027DF5960BA9EF");

                    b.HasIndex("Product3DModelId")
                        .IsUnique()
                        .HasFilter("[product_3d_model_id] IS NOT NULL");

                    b.HasIndex(new[] { "Product3DModelId" }, "IX_Product_3d_Model_id");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Product_category_id");

                    b.HasIndex(new[] { "Slug" }, "IX_Product_slug")
                        .IsUnique()
                        .HasFilter("([slug] IS NOT NULL)");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Product3DModel", b =>
                {
                    b.Property<long>("Product3DModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_3d_model_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Product3DModelId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<string>("ModelUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model_url");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("video_url");

                    b.HasKey("Product3DModelId")
                        .HasName("PK__Product3__7A982983809D9053");

                    b.ToTable("Product3DModel", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductFavorite", b =>
                {
                    b.Property<long>("ProductFavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_d");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductFavoriteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductFavoriteId");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductFavorite_ProductId");

                    b.HasIndex(new[] { "UserId" }, "IX_ProductFavorite_UserId");

                    b.ToTable("ProductFavorite", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductImage", b =>
                {
                    b.Property<long>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("productImage_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("image_url");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.HasKey("ProductImageId")
                        .HasName("PK__ProductI__7A342910809D9053");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductImage_product_id");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductReport", b =>
                {
                    b.Property<long>("ProductReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<long>("ProductReportedId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_reported_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<long>("ReportStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_report_id");

                    b.HasKey("ProductReportId")
                        .HasName("PK__ProductR__DC0B4A22C1B82B5E");

                    b.HasIndex(new[] { "ProductReportedId" }, "IX_ProductReport_product_reported_id");

                    b.HasIndex(new[] { "ReportStatusId" }, "IX_ProductReport_report_status_id");

                    b.HasIndex(new[] { "UserReportId" }, "IX_ProductReport_user_report_id");

                    b.ToTable("ProductReport", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductReview", b =>
                {
                    b.Property<long>("ProductReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductReviewId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Rate")
                        .HasColumnType("int")
                        .HasColumnName("rate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ProductReviewId")
                        .HasName("PK__ProductR__8440EB03DB89B961");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductReview_product_id");

                    b.HasIndex(new[] { "UserId" }, "IX_ProductReview_user_id");

                    b.ToTable("ProductReview", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductReviewInteraction", b =>
                {
                    b.Property<long>("ProductReviewInteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_review_interaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductReviewInteractionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<long>("ProductInteractionStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_interaction_status_id");

                    b.Property<long>("ProductReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_review_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ProductReviewInteractionId")
                        .HasName("PK__ProductI__A2F12EDBBAC0359E");

                    b.HasIndex(new[] { "ProductInteractionStatusId" }, "IX_ProductReviewInteraction_product_interaction_status_id");

                    b.HasIndex(new[] { "ProductReviewId" }, "IX_ProductReviewInteraction_product_review_id");

                    b.HasIndex(new[] { "UserId" }, "IX_ProductReviewInteraction_user_id");

                    b.ToTable("ProductReviewInteraction", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ProductReviewInteractionStatus", b =>
                {
                    b.Property<long>("ProductReviewInteractionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_review_interaction_status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductReviewInteractionStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("ProductReviewInteractionStatusId")
                        .HasName("PK__ProductI__0CC0092882FD7968");

                    b.ToTable("ProductReviewInteractionStatus", (string)null);
                });

            modelBuilder.Entity("BusinessObject.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("refresh_token_id");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expired_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jwt_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex(new[] { "UserId" }, "IX_RefreshToken_user_id");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ReportProductReview", b =>
                {
                    b.Property<long>("ReportProductReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("report_product_review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportProductReviewId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<long>("ProductReviewReportedId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_review_reported_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<long>("ReportStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_report_id");

                    b.HasKey("ReportProductReviewId")
                        .HasName("PK__ReportPr__09EE80B34DFBA358");

                    b.HasIndex(new[] { "ProductReviewReportedId" }, "IX_ReportProductReview_product_review_reported_id");

                    b.HasIndex(new[] { "ReportStatusId" }, "IX_ReportProductReview_report_status_id");

                    b.HasIndex(new[] { "UserReportId" }, "IX_ReportProductReview_user_report_id");

                    b.ToTable("ReportProductReview", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ReportStatus", b =>
                {
                    b.Property<long>("ReportStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("report_status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("ReportStatusId")
                        .HasName("PK__ReportSt__09E0D88687C41A16");

                    b.ToTable("ReportStatus", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__760965CC5F8795DF");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("EmailConfirmationCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("email_confirmation_code");

                    b.Property<DateTime?>("EmailConfirmationSentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("email_confirmation_sent_at");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<bool>("IsSubscriber")
                        .HasColumnType("bit")
                        .HasColumnName("is_subscriber");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("ResetPasswordCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("reset_password_code");

                    b.Property<bool>("ResetPasswordRequired")
                        .HasColumnType("bit")
                        .HasColumnName("reset_password_required");

                    b.Property<DateTime?>("ResetPasswordSentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reset_password_sent_at");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK__User__B9BE370F0AD19949");

                    b.HasIndex(new[] { "RoleId" }, "IX_User_role_id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("BusinessObject.UserAddress", b =>
                {
                    b.Property<long>("UserAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_address_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserAddressId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("is_delete");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("UserAddressId")
                        .HasName("PK__UserAddr__FEC0352E4E3DC7B4");

                    b.HasIndex(new[] { "UserId" }, "IX_UserAddress_user_id");

                    b.ToTable("UserAddress", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Article", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Article_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Cart", b =>
                {
                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Cart_Product");

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Cart_User");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Chat", b =>
                {
                    b.HasOne("BusinessObject.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .IsRequired()
                        .HasConstraintName("FK_Message_User1");

                    b.HasOne("BusinessObject.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_Message_User");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BusinessObject.Coupon", b =>
                {
                    b.HasOne("BusinessObject.CouponType", "CouponType")
                        .WithMany("Coupons")
                        .HasForeignKey("CouponTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Coupon_CouponType");

                    b.Navigation("CouponType");
                });

            modelBuilder.Entity("BusinessObject.Notification", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Order", b =>
                {
                    b.HasOne("BusinessObject.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK_Order_Coupon");

                    b.HasOne("BusinessObject.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_OrderStatus");

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_User");

                    b.Navigation("Coupon");

                    b.Navigation("OrderStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.OrderDetail", b =>
                {
                    b.HasOne("BusinessObject.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetail_Order");

                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetail_Product");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObject.Product", b =>
                {
                    b.HasOne("BusinessObject.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("BusinessObject.Product3DModel", "Product3DModel")
                        .WithOne("Product")
                        .HasForeignKey("BusinessObject.Product", "Product3DModelId");

                    b.Navigation("Category");

                    b.Navigation("Product3DModel");
                });

            modelBuilder.Entity("BusinessObject.ProductFavorite", b =>
                {
                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("ProductFavorites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("ProductFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.ProductImage", b =>
                {
                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductImage_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObject.ProductReport", b =>
                {
                    b.HasOne("BusinessObject.Product", "ProductReported")
                        .WithMany("ProductReports")
                        .HasForeignKey("ProductReportedId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReport_Product");

                    b.HasOne("BusinessObject.ReportStatus", "ReportStatus")
                        .WithMany("ProductReports")
                        .HasForeignKey("ReportStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReport_ReportStatus");

                    b.HasOne("BusinessObject.User", "UserReport")
                        .WithMany("ProductReports")
                        .HasForeignKey("UserReportId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReport_User");

                    b.Navigation("ProductReported");

                    b.Navigation("ReportStatus");

                    b.Navigation("UserReport");
                });

            modelBuilder.Entity("BusinessObject.ProductReview", b =>
                {
                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReview_Product");

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("ProductReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReview_User");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.ProductReviewInteraction", b =>
                {
                    b.HasOne("BusinessObject.ProductReviewInteractionStatus", "ProductReviewInteractionStatuses")
                        .WithMany("ProductReviewInteractions")
                        .HasForeignKey("ProductInteractionStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReviewInteraction_ProductReviewInteractionStatus");

                    b.HasOne("BusinessObject.ProductReview", "ProductReview")
                        .WithMany("ProductReviewInteractions")
                        .HasForeignKey("ProductReviewId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReviewInteraction_Product");

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("ProductInteractions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReviewInteraction_User");

                    b.Navigation("ProductReview");

                    b.Navigation("ProductReviewInteractionStatuses");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.RefreshToken", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.ReportProductReview", b =>
                {
                    b.HasOne("BusinessObject.ProductReview", "ProductReviewReported")
                        .WithMany("ReportProductReviews")
                        .HasForeignKey("ProductReviewReportedId")
                        .IsRequired()
                        .HasConstraintName("FK_ReportProductReview_ProductReview");

                    b.HasOne("BusinessObject.ReportStatus", "ReportStatus")
                        .WithMany("ReportProductReviews")
                        .HasForeignKey("ReportStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_ReportProductReview_ReportStatus");

                    b.HasOne("BusinessObject.User", "UserReport")
                        .WithMany("ReportProductReviews")
                        .HasForeignKey("UserReportId")
                        .IsRequired()
                        .HasConstraintName("FK_ReportProductReview_User");

                    b.Navigation("ProductReviewReported");

                    b.Navigation("ReportStatus");

                    b.Navigation("UserReport");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.HasOne("BusinessObject.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.UserAddress", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAddress_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessObject.Coupon", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BusinessObject.CouponType", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("BusinessObject.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BusinessObject.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BusinessObject.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductFavorites");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductReports");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("BusinessObject.Product3DModel", b =>
                {
                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObject.ProductReview", b =>
                {
                    b.Navigation("ProductReviewInteractions");

                    b.Navigation("ReportProductReviews");
                });

            modelBuilder.Entity("BusinessObject.ProductReviewInteractionStatus", b =>
                {
                    b.Navigation("ProductReviewInteractions");
                });

            modelBuilder.Entity("BusinessObject.ReportStatus", b =>
                {
                    b.Navigation("ProductReports");

                    b.Navigation("ReportProductReviews");
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Carts");

                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("ProductFavorites");

                    b.Navigation("ProductInteractions");

                    b.Navigation("ProductReports");

                    b.Navigation("ProductReviews");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReportProductReviews");

                    b.Navigation("UserAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
